spring.application.name=kost-management

# GUNAKAN FORMAT INI AGAR BISA JALAN DI LAPTOP & RAILWAY SEKALIGUS:
spring.datasource.url=jdbc:mysql://${MYSQLHOST:127.0.0.1}:${MYSQLPORT:3306}/${MYSQLDATABASE:kost_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Username & Password Fleksibel
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}

# Driver & Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}